import Link from 'next/link'
import './globals.css'

export const metadata = {
  title: 'Web tutorial',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  
  return (
    <html>
      <body>
        <table>
          <thead>
          <tr>
            <td><h1><Link href="/home">WEB</Link></h1></td>
            <td><h1> / </h1></td>
            <td><h1><Link href="/crud">CRUD</Link></h1></td>
            <td><h1> / </h1></td>
            <td><h1><Link href="/hooks">HOOKS</Link></h1></td>
            <td><h1> / </h1></td>
            <td><h1><Link href="/game">GAME</Link></h1></td>
          </tr>
          </thead>
        </table>

        {children}
        
      </body>
    </html>
  )
}
